import "./globals.css";
import Navbar from "@/components/Navbar";
import { LoopContextProvider } from "@/components/LoopContext";
import { LoginContextProvider } from "@/components/LoginContext";
import Footer from "@/components/Footer";

export const metadata = {
	title: "LOOP",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body >
				<LoopContextProvider>
					<LoginContextProvider>
						<Navbar />
						{children}
						<Footer />
					</LoginContextProvider>
				</LoopContextProvider>
			</body>
		</html>
	);
}
