import "./globals.css";
import Navbar from "@/components/Navbar";
import { LoopContextProvider } from "@/components/LoopContext";
import { LoginContextProvider } from "@/components/LoginContext";
import Footer from "@/components/Footer";
import { ChatGPTContextProvider } from "@/components/ChatGPTContext";
import ChatGPTModal from "@/components/ChatGPTModal";

export const metadata = {
	title: "LOOP",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ChatGPTContextProvider>
					<LoopContextProvider>
						<LoginContextProvider>
							<ChatGPTModal />

							<Navbar />
							{children}
							<Footer />
						</LoginContextProvider>
					</LoopContextProvider>
				</ChatGPTContextProvider>
			</body>
		</html>
	);
}
