import "./globals.css";
import Navbar from "@/components/Navbar";
import { LoopContextProvider } from "@/components/LoopContext";

export const metadata = {
	title: "LOOP",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<LoopContextProvider>
					<Navbar />
					{children}
				</LoopContextProvider>
			</body>
		</html>
	);
}
