const solutions = {
	NY: [
		{
			// Alt text for the image
			alt: "Solar Panels on a Independent Home",

			// Preferably as numbers, i'll fix it
			gov: 1000,
			utility: 5000,
			price: 18000,

			// On a scale from 1 to 5
			setup: 3,

			// Image link
			image: "/solutions/solar_panel.jpg",

			// Name of the solution
			title: "Solar Panels",

			// Some interesting stats
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],

			// Description of the solution
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",

			// Applicable home types
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],

			// Type of solution (one of the five we chose before)
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "transportation",
		},
	],
	WA: [
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "transportation",
		},
	],
	TX: [
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			type: "transportation",
		},
	],
};

export default solutions;
