const solutions = [
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "electricity",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "electricity",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "water",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "water",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "waste",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "waste",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "heating",
	},
	{
		alt: "Solar Panels on a Independent Home",
		gov: "$1K",
		utility: "$5K",
		price: "~$18K",
		setup: 3,
		image: "/solutions/solar_panel.jpg",
		title: "Solar Panels",
		type: "transportation",
	},
];

export default solutions;
