const solutions = {
	NY: [
		{
			// Alt text for the image
			alt: "Solar Panels on a Independent Home",

			// Preferably as numbers, i'll fix it
			gov: 1000,
			utility: 5000,
			price: 18000,

			// On a scale from 1 to 5
			setup: 3,

			// Image link
			image: "/solutions/solar_panel.jpg",

			// Name of the solution
			title: "Solar Panels",

			// Some interesting stats
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],

			// Description of the solution
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",

			// Applicable home types
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],

			//Installation steps:
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],

			// Type of solution (one of the five we chose before)
			type: "electricity",

			// Points on the cost graph
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],

			// Points on the ROI graph
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],

			// Rebates by category
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "transportation",
		},
	],
	WA: [
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "transportation",
		},
	],
	TX: [
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "electricity",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "water",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "waste",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "heating",
		},
		{
			alt: "Solar Panels on a Independent Home",
			gov: 1000,
			utility: 5000,
			price: 18000,
			setup: 3,
			image: "/solutions/solar_panel.jpg",
			title: "Solar Panels",
			stats: [
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
				{ data: 200, units: "lbs/kwh", description: "CO2 prevented from emissions" },
			],
			description: "Installed in areas with high sunlight exposure such as rooftops and balconies, these silicon-based panels harness sunlight to produce electricity. ",
			hometypes: ["Apartment", "Multi-Family Home", "Individual Home"],
			costGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			roiGraph: [
				[1985, 30000],
				[1990, 18000],
				[1995, 16000],
				[2000, 13500],
				[2005, 13000],
				[2010, 11500],
				[2015, 10500],
				[2020, 10000],
				[2025, 5000],
			],
			steps: [
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
				{ header: "Find a Provider", description: "Important factors when choosing an provider include: warranties, installation costs, and disposal of the old system." },
			],
			utilityRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			govtRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			taxRebates: [
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
				{ price: 500, label: "For solar panels installed in a home" },
			],
			type: "transportation",
		},
	],
};

export default solutions;
