const sources = [
	{
		name: "New York",
		sources: [
			"Herreros-Cantis, P., & McPhearson, T. (2021). Mapping supply of and demand for ecosystem services to assess environmental justice in New York City. Ecological Applications",
			"A comprehensive look at food system vulnerability: Impacts and adaptation. In A Bibliography: Key References on Climate Change (Appendix)Climate Impacts Group, University of Washington",
			"Metcalf & Eddy Inc. (n.d.). Wastewater engineering: Treatment and resource recovery. Retrieved from BibGuru",
			"García, M., & Patel, S. Promoting rooftop gardens for urban sustainability: A case study in New York City. Sustainable Cities and Society",
			"(2018). Assessing the impact of green roofs on urban heat island mitigation in New York City. Urban Forestry & Urban Greening",
			"Urban agriculture in New York City: Community gardens and beyond. Urban Geography, 36(4),",
			"Evaluating the effectiveness of green infrastructure for stormwater management in New York City. Journal of Hydrology",
			"Peters, C., & Turner, W. (2014). Urban forestry in New York: Challenges and opportunities. Arboriculture & Urban Forestry.",
			"Wu, J., & Li, H. (2018). Assessing the impact of green spaces on air quality in New York City. Environmental Pollution,",
			"Community-based climate adaptation in New York neighborhoods. Climate Policy, 17(1).",
			"Gómez-Baggethun, Classifying and valuing ecosystem services for urban planning. Ecological Economics, 86,",
			"(2017). Urban ecology in New York City: An assessment of current conditions and trends. Frontiers in Ecology and the Environment",
			"García, R., & Patel, S. (2019). Urban green roofs as a strategy for climate adaptation in New York City. Urban Climate",
			"Chowdhury, R., & Rahman, M, Assessing the impact of green infrastructure on air quality in New York neighborhoods. Environmental Science and Pollution Research,",
			"Evaluating the effectiveness of urban forests in mitigating heat island effects in New York. Urban Ecosystems,",
			"Harris, J., & Turner, W. Community-based conservation initiatives for New York wetlands. Wetlands Ecology and Management,",
			"(2015). Promoting sustainable transportation in New York City: A case study of bike-sharing programs. Transportation Research Part D: Transport and Environment,",
			"(2014). Assessing the role of urban parks in enhancing biodiversity in New York. Biodiversity and Conservation",
			"(2013). Urban green spaces and mental well-being: A study in New York neighborhoods. Landscape and Urban Planning,",
			"(2012). Ecosystem services in urban areas: A case study of New York City. Ecological Economics,",
			"(2011). Urban biodiversity in New York: Challenges and opportunities. Frontiers in Ecology and the Environment",
			"Lee, S., & Wang, J. (Assessing the impact of green roofs on stormwater management in New York City. Journal of Environmental Management.",
			"(2009). Urban forestry and carbon sequestration in New York. Urban Forestry & Urban Greening, 8(2),",
			"Sustainable Development Solutions Network. (n.d.). Home. Retrieved from https://www.unsdsn.org/",
			"City of New York. (n.d.). Urban sustainability. Retrieved from https://www.nyc.gov/site/sustainability/initiatives/urban-sustainability.pageColumbia Climate School. (2023, April 24).",
			"Getting sustainability done in New York City. Retrieved from https://news.climate.columbia.edu/2023/04/24/getting-sustainability-done-in-new-york-city/Ecobnb. (2018, December).",
			"New York: A sustainable city. Retrieved from https://ecobnb.com/blog/2018/12/new-york-sustainable-city/Tech:NYC. (2019, April).",
			"Five sustainability-minded companies to watch - April 2019. Retrieved from https://www.technyc.org/posts/five-sustainability-minded-companies-to-watch-april-2019",
			"New York State Energy Research and Development Authority. (n.d.). Home. Retrieved from https://www.nyserda.ny.gov/",
			"City of New York. (n.d.). Climate action tracker. Retrieved from https://www.nyc.gov/site/sustainability/initiatives/climate-action-tracker.page",
			"New York State Department of Environmental Conservation. (n.d.). Home. Retrieved from https://www.dec.ny.gov/",
		],
	},
	{
		name: "Texas",
		sources: [
			"Accounts, T. C. of P. (n.d.). Solar Energy is Good for Texas. Comptroller.texas.gov. Retrieved March 2, 2024, from https://comptroller.texas.gov/economy/economic-data/energy/2023/solar-snap.php",
			"Alternative Fuels Data Center: Electricity Laws and Incentives in Texas. (n.d.). Afdc.energy.gov. https://afdc.energy.gov/fuels/laws/ELEC?state=TX",
			"Burkhart, R. (2023, September 6). Oil-Capturing Technology Offers 10x Improvement Cleaning Up Hazardous Spills. UT News. https://news.utexas.edu/2023/09/06/oil-capturing-technology-offers-10x-improvement-cleaning-up-hazardous-spills/",
			"Casey, T. (2023, December 30). Texas Is Going To Send Lots Of Solar Modules All Over The USA. CleanTechnica. https://cleantechnica.com/2023/12/30/solar-modules-texas-jobs-usa-india/",
			"Energy Efficient Windows Texas | Low-E Glass Window Installation. (n.d.). Home Remodeling - Bathrooms, Windows, & More | Statewide. Retrieved March 2, 2024, from https://www.statewideremodeling.com/windows/energy-efficient-windows/",
			"Harab, G. H., HPM Intern, Matt. (2020, November 11). TCEQ Unveils New Technology For Monitoring Air Pollution During Hurricanes And Other Disasters. Houston Public Media. https://www.houstonpublicmedia.org/articles/news/energy-environment/2020/11/11/385992/tceq-unveils-new-technology-for-monitoring-air-pollution-during-hurricanes-and-other-disasters/",
			"Harrison, D. (2023, December 26). “Major” Problem in Texas: How Big Polluters Evade Federal Law and Get Away With It. Inside Climate News. https://insideclimatenews.org/news/26122023/state-of-denial-texas-polluters-evade-federal-law/",
			"Heat Pump vs AC in Texas - Which is Better? | Jon Wayne. (n.d.). Heat Pump vs AC in Texas - Which Is Better? | Jon Wayne. Retrieved March 2, 2024, from https://jonwayne.com/articles/heat-pump-vs-ac-texas",
			"Henson, B. (n.d.). Heat pumps are catching on. New rebates, tax breaks may turbocharge the trend. Texas Climate News. Retrieved March 2, 2024, from https://texasclimatenews.org/2023/03/02/heat-pumps-are-catching-on-new-rebates-tax-breaks-may-turbocharge-the-trend/",
			"Make Your Home More Energy Efficient: Texas. (n.d.). HUD.gov / U.S. Department of Housing and Urban Development (HUD). https://www.hud.gov/states/texas/homeownership/energy",
			"Metzger, L. (2023, January 23). What Texans needs to know about heat pumps. Environmentamerica.com. https://environmentamerica.org/texas/center/articles/what-texans-needs-to-know-about-heat-pumps/",
			"NCEI.Monitoring.Info@noaa.gov. (n.d.). Billion-Dollar Weather and Climate Disasters | National Centers for Environmental Information (NCEI). Www.ncei.noaa.gov. https://www.ncei.noaa.gov/access/billions/state-summary/TX",
			"New Solar Modules. (n.d.). Texas Solar Group. Retrieved March 2, 2024, from https://texassolargroup.com/new-solar-modules/",
			"path environmental technology. (n.d.). Path Enviro. Retrieved March 2, 2024, from https://www.pathenviro.com/",
			"Power, T. C. (n.d.). Explore Expanded Tax Credits for Energy Efficiency. Texas Co-Op Power. Retrieved March 2, 2024, from https://texascooppower.com/explore-expanded-tax-credits-for-energy-efficiency/",
			"Pros and Cons of a Heat Pump for Your Texas Home. (n.d.). Smart AC Services. Retrieved March 2, 2024, from https://smartacservices.com/about-us/blog/pros-and-cons-of-a-heat-pump-for-your-texas-home-3",
			"Spiller, E., Sopher, P., Martin, N., Mirzatuny, M., & Zhang, X. (2017). The environmental impacts of green technologies in TX. Energy Economics, 68, 199–214. https://doi.org/10.1016/j.eneco.2017.09.009",
			"Texas Solar Incentives, Tax Credits and Rebates Guide For Going Solar in Texas. (2023, September 8). Forbes. https://www.forbes.com/home-improvement/solar/texas-solar-incentives/",
			"Texas Weatherization Assistance Program | Benefits.gov. (n.d.). Www.benefits.gov. Retrieved March 2, 2024, from https://www.benefits.gov/benefit/1883",
			"US EPA, O. (2013, January 29). EPA Region 6 (South Central). Www.epa.gov. https://www.epa.gov/aboutepa/epa-region-6-south-central",
			"US EPA, O. (2023, November 29). EPA Awards Nearly $500,000 to Texas Organization to improve Air Quality in the Houston Area. Www.epa.gov. https://www.epa.gov/newsreleases/epa-awards-nearly-500000-texas-organization-improve-air-quality-houston-area",
			"US EPA, O. (2024a, February 22). Biden-Harris Administration announces $358,980,000 for Texas to Upgrade Drinking Water, Wastewater and Stormwater Infrastructure as part of President Biden’s Investing in America agenda. Www.epa.gov. https://www.epa.gov/newsreleases/biden-harris-administration-announces-358980000-texas-upgrade-drinking-water",
			"US EPA, O. (2024b, February 28). Biden-Harris Administration announces new cleanup project in Texas as part of President Biden’s Investing in America agenda. Www.epa.gov. https://www.epa.gov/newsreleases/biden-harris-administration-announces-new-cleanup-project-texas-part-president-bidens",
			"US EPA, R. 06. (2015a, February 3). Cleanups in Texas. Www.epa.gov. https://www.epa.gov/tx/cleanups-texas",
			"US EPA, R. 06. (2015b, March 26). Water in Texas. Www.epa.gov. https://www.epa.gov/tx/water-texas",
			"US EPA, R. 06. (2015c, April 17). Air Issues in Texas. US EPA. https://www.epa.gov/tx/air-issues-texas",
		],
	},
	{
		name: "Washington",
		sources: [
			"University of Washington Sustainability. (n.d.). Research. Retrieved from https://sustainability.uw.edu/research",
			"Washington State Department of Commerce. (n.d.). Energy. Retrieved from https://www.commerce.wa.gov/energy/",
			"Washington State Department of Transportation. (n.d.). Sustainability. Retrieved from https://wsdot.wa.gov/environment/sustainability",
			"Washington State Department of Ecology. (n.d.). Climate change. Retrieved from https://ecology.wa.gov/climate-change/",
			"Washington Department of Fish and Wildlife. (n.d.). Conservation. Retrieved from https://wdfw.wa.gov/conservation/",
			"Washington State Department of Commerce. (n.d.). Housing. Retrieved from https://www.commerce.wa.gov/housing/",
			"Washington State Department of Commerce. (n.d.). Clean energy. Retrieved from https://www.commerce.wa.gov/clean-energy/",
			"Washington State Department of Natural Resources. (n.d.). Climate change adaptation. Retrieved from https://www.dnr.wa.gov/climate-change-adaptation/",
			"Washington State Department of Ecology. (n.d.). Water quality. Retrieved from https://www.ecology.wa.gov/Water-Shorelines/Water-quality/",
			"Washington State Department of Commerce. (n.d.). Green building. Retrieved from https://www.commerce.wa.gov/green-building/",
			"Washington State Department of Health. (n.d.). Climate and health. Retrieved from https://www.doh.wa.gov/CommunityandEnvironment/Climate/Health/",
			"Washington Department of Fish and Wildlife. (n.d.). Habitat conservation. Retrieved from https://wdfw.wa.gov/conservation/habitat/",
			"Washington State Department of Commerce. (n.d.). Renewable energy. Retrieved from https://www.commerce.wa.gov/renewable-energy/",
			"Washington State Department of Ecology. (n.d.). Air quality. Retrieved from https://ecology.wa.gov/Air-Climate/Air-quality/",
			"Washington State Department of Commerce. (n.d.). Sustainable communities. Retrieved from https://www.commerce.wa.gov/sustainable-communities/",
			"Washington State Department of Commerce. (n.d.). Climate action. Retrieved from https://www.commerce.wa.gov/climate-action/",
			"Washington State Department of Commerce. (n.d.). Energy. Retrieved from https://www.commerce.wa.gov/energy/",
			"Washington State Department of Natural Resources. (n.d.). Geodiversity. Retrieved from https://www.dnr.wa.gov/geodiversity/",
		],
	},
	{
		name: "Product Images",
		sources: [
			"The Home Depot. (n.d.). Types of LED Lights. Retrieved from https://www.homedepot.com/c/ab/types-of-led-lights/9ba683603be9fa5395fab9011a91d53",
			"Gengler, R. (2020, August 19). Does an energy monitor really add value to a smart home? Restechtoday. Retrieved from https://restechtoday.com/does-an-energy-monitor-really-add-value-to-a-smart-home/",
			"Stewart, M. (2021, November 10). Best Smart Thermostats of 2021. Reviews.org. Retrieved from https://www.reviews.org/home-security/best-smart-thermostats/",
			"Treehugger. (n.d.). 10 Best Energy-Efficient Refrigerators for 2021. Retrieved from https://www.treehugger.com/energy-efficient-refrigerators-5193342",
			"Tennessee Magazine. (n.d.). Is a geothermal heat pump right for you? Retrieved from https://www.tnmagazine.org/is-a-geothermal-heat-pump-right-for-you/",
			"Micro-Hydro-Power.com. (n.d.). Retrieved from https://www.micro-hydro-power.com/",
			"altE. (n.d.). Residential Wind Turbines: Are They Practical for You? Retrieved from https://www.altestore.com/diy-solar-resources/residential-wind-turbines-practical-for-you/",
			"Lowimpact.org. (n.d.). Composting Toilets and City Flats – Do They Match? Retrieved from https://www.lowimpact.org/posts/composting-toilets-and-city-flats-do-they-match",
			"The Home Depot. (n.d.). Best High-Efficiency Washing Machines for Your Home. Retrieved from https://www.homedepot.com/c/ab/best-high-efficiency-washing-machines-for-your-home/9ba683603be9fa5395fab90c4e9a308",
			"Virginia Association of Soil and Water Conservation Districts. (n.d.). Permeable Pavement Installation. Retrieved from https://vaswcd.org/permeable-pavement-installation/",
			"Zone7 Water. (n.d.). Rebate on Smart Irrigation Controllers. Retrieved from https://www.zone7water.com/post/rebate-smart-irrigation-controllers",
			"(n.d.). 5 Xeriscaping Myths, Debunked. Retrieved from https://www.5280.com/5-xeriscaping-myths-debunked/",
			"Lawn Love. (n.d.). Benefits of Drip Irrigation. Retrieved from https://lawnlove.com/blog/benefits-of-drip-irrigation/",
			"Niccolini, L. (2016, May 12). Sunrun begins installing Tesla home batteries. Computerworld. Retrieved from https://www.computerworld.com/article/3069499/sunrun-begins-installing-tesla-home-batteries.html",
			"Watts. (n.d.). Hydronic Heating Systems. Retrieved from https://www.watts.com/solutions/systems/hydronic-heating-systems",
			"Delaney, E. (2016, February 3). What's Typical for Average Daily Steps? Verywell Fit. Retrieved from https://www.verywellfit.com/whats-typical-for-average-daily-steps-3435736",
			"The Home Depot. (n.d.). US Stove Wiseway 2,000 sq. ft. 40,000 BTU Non-Electric Gravity Fed Pellet Stove. Retrieved from https://www.homedepot.com/p/US-Stove-Wiseway-2-000-sq-ft-40-000-BTU-Non-Electric-Gravity-Fed-Pellet-Stove-GW1949/206691061",
			"Energy Saving Trust. (n.d.). Solar Water Heating. Retrieved from https://energysavingtrust.org.uk/advice/solar-water-heating/",
			"Modernize. (n.d.). Electric Boiler: When to Use One and What It Costs to Run. Retrieved from https://modernize.com/homeowner-resources/hvac/electric-boiler-when-to-use-one-and-what-it-costs-to-run",
			"University of North Carolina at Chapel Hill. (n.d.). Infrastructure Needed for E-Scooter Safety. Retrieved from https://www.unc.edu/discover/infrastructure-needed-for-e-scooter-safety/",
			"U.S. News & World Report. (n.d.). 15 Cheapest Hybrid Cars in 2023. Retrieved from https://cars.usnews.com/cars-trucks/advice/cheapest-hybrid-cars",
			"French, C. (2020, March 24). Tools Needed for Telecommuting. Federal Trade Commission. Retrieved from https://www.ftc.net/business/blog/tools-needed-for-telecommuting/",
			"Gille, M. (2019, August 6). The Benefits of Carpooling. MaskMatters. Retrieved from https://www.maskmatters.org/carpool/",
			"Port of Seattle. (n.d.). Public Transit. Retrieved from https://www.portseattle.org/sea-tac/ground-transportation/public-transit",
			"Grassracks. (n.d.). Bike Wall Rack. Retrieved from https://www.grassracks.com/products/bike-wall-rack",
			"Kahn, J. (2020, February 12). Cost to Install Wall Insulation. Forbes. Retrieved from https://www.forbes.com/home-improvement/insulation/cost-to-install-wall-insulation/",
			"Yang, S. (2017, June 5). How Chinese automaker Geely is expanding its global reach. China Daily. Retrieved from https://www.chinadaily.com.cn/business/motoring/2017-06/05/content_29614147.htm",
			"eBay. (n.d.). eBay Listing for Rainwater Harvesting Tank. Retrieved from https://www.ebay.com/itm/145547420112",
			"Builder Online. (n.d.). Low-Flow Fixtures from Fluid_O. Retrieved from https://www.builderonline.com/products/green-products/low-flow-fixtures-from-fluid_o",
			"Complete Landscaping Service. (n.d.). Xeriscaping Can Help Save Water. Retrieved from https://completelandscaping.com/xeriscaping-can-help-save-water/",
			"Agrivi. (n.d.). Drip Irrigation as the Most Efficient Irrigation System Type. Retrieved from https://www.agrivi.com/blog/drip-irrigation-as-the-most-efficient-irrigation-system-type/",
			"Tavistock Bathrooms. (n.d.). Quantum Dual Function Shower System. Retrieved from https://www.tavistock-bathrooms.co.uk/quantum-dual-function-shower-system-with-handset-holder-overhead-shower-chrome",
			"Amazon.com. (n.d.). NINILADY Vertical Turbine Generator with Controller. Retrieved from https://www.amazon.com/NINILADY-Vertical-Turbine-Generator-Controller/dp/B08MQ8PQ7D",
			"TechHive. (n.d.). Ring A19 Smart LED Bulb review: Ring shines bright. Retrieved from https://www.techhive.com/article/578519/ring-a19-smart-led-bulb-review.html",
			"Google Nest Learning Smart WiFi Thermostat. (n.d.). Retrieved from https://aspaen.edu.co/?w=google-nest-learning-smart-wifi-thermostat-black-t3018us-best-ee-o27Y4OhZ",
			"PMC Architects. (n.d.). When Will a Tesla Home Battery Pay for Itself? Retrieved from https://www.pmcarchitects.com/sustainability-information-blog-content/when-will-a-tesla-home-battery-pay-for-itself",
			"Wikipedia. (n.d.). Carsharing. Retrieved from https://en.wikipedia.org/wiki/Carsharing",
			"Cars.com. (n.d.). What Are Hydrogen Cars? Retrieved from https://www.cars.com/articles/what-are-hydrogen-cars-442319/",
			"Freepik. (n.d.). Web Conference Business Online Corporate Telecommuting Man Holding Laptop with Professional Team Working on Project Screen Virtual Office Isolated Black. Retrieved from https://www.freepik.com/premium-photo/web-conference-business-online-corporate-telecommuting-man-holding-laptop-with-professional-team-working-project-screen-virtual-office-isolated-black_24955614.htm",
			"Davidson, J. (2018, January 30). Breaking Down New York City's Bus Operating Costs. Curbed NY. Retrieved from https://ny.curbed.com/2018/1/30/16946476/mta-new-york-city-bus-operating-costs-analysis",
			"Car and Driver. (n.d.). 2023 Tesla Model S. Retrieved from https://www.caranddriver.com/tesla/model-s-2023",
			"Etsy. (n.d.). Rustic Kentucky Crapper Composting Toilet. Retrieved from https://www.etsy.com/listing/1048894021/rustic-kentucky-crapper-composting",
			"Lowe's. (n.d.). Rubbermaid Commercial Products Brute 50-Gallon Blue Commercial Outdoor Recycling Bin with Lid. Retrieved from https://www.lowes.com/pd/Rubbermaid-Commercial-Products-Brute-50-Gallon-Blue-Commercial-Outdoor-Recycling-Bin-with-Lid/50335461",
			"Wills, T. (2019, March 11). Passive Solar Design vs. Passive House. Architecture & Design. Retrieved from https://www.architectureanddesign.com.au/features/comment/passive-solar-design-vs-passive-house",
			"American Thermal Window. (n.d.). The Benefits of Triple Pane Windows. Retrieved from https://americanthermalwindow.com/benefits-triple-pane-windows/",
			"Ace Hardware. (n.d.). Frost King 12 ft. Foam Plumbing Tubular Pipe Insulation. Retrieved from https://www.acehardware.com/departments/plumbing/winterization/pipe-insulation/4565685?x429=true&gad_source=1&gclid=CjwKCAiAloavBhBOEiwAbtAJO6TB71_FNCmHT9v3fwMZhPzks7am3pOS1vLMBFlMZ9U_KITgnmPpARoCnTMQAvD_BwE&gclsrc=aw.ds",
			"Air Management. (n.d.). Heat Pumps. Retrieved from https://airmanagement.com/heat-pumps/",
			"Complete Insulations. (n.d.). Earthwool Attic Insulation. Retrieved from https://www.completeinsulations.ie/earthwool-attic-insulation/",
			"LG. (n.d.). LG WM3470CM Front Load Washer. Retrieved from https://www.lg.com/us/washers-dryers/lg-wm3470cm-front-load-washer",
			"Fuji Bikes. (n.d.). Fuji Absolute 21. Retrieved from https://www.fujibikes.com/products/absolute-21-21",
			"Weil-McLain. (n.d.). Full Line of Weil-McLain Products. Retrieved from https://www.weil-mclain.com/full-line",
		],
	},
	{
		name: "Icons",
		sources: [
			"Iconify. (n.d.). Water Icon. Retrieved from https://icon-sets.iconify.design/ion/water/",
			"Iconify. (n.d.). Lightbulb Icon. Retrieved from https://icon-sets.iconify.design/material-symbols/lightbulb/",
			"Iconify. (n.d.). Car Icon. Retrieved from https://icon-sets.iconify.design/ion/car/",
			"Iconify. (n.d.). Fire Icon. Retrieved from https://icon-sets.iconify.design/fluent/fire-24-filled/",
			"Iconify. (n.d.). Add Icon. Retrieved from https://icon-sets.iconify.design/fluent/add-16-filled/",
			"Iconify. (n.d.). Trash Icon. Retrieved from https://icon-sets.iconify.design/lets-icons/trash/",
			"Iconify. (n.d.). Move Up Icon. Retrieved from https://icon-sets.iconify.design/lucide/move-up/",
			"Iconify. (n.d.). Grab Vertical Icon. Retrieved from https://icon-sets.iconify.design/charm/grab-vertical/",
			"Iconify. (n.d.). Company Icon. Retrieved from https://icon-sets.iconify.design/mdi/company/",
			"Iconify. (n.d.). Gavel Icon. Retrieved from https://icon-sets.iconify.design/material-symbols/gavel/",
			"Iconify. (n.d.). Hammer Icon. Retrieved from https://icon-sets.iconify.design/f7/hammer-fill/",
			"Iconify. (n.d.). Search Icon. Retrieved from https://icon-sets.iconify.design/tabler/search/",
			"Iconify. (n.d.). Leaf Icon. Retrieved from https://icon-sets.iconify.design/mingcute/leaf-fill/",
			"Iconify. (n.d.). Money Off Icon. Retrieved from https://icon-sets.iconify.design/ic/outline-money-off/",
			"Iconify. (n.d.). Filter Icon. Retrieved from https://icon-sets.iconify.design/fluent/filter-12-filled/",
			"Iconify. (n.d.). Sort Icon. Retrieved from https://icon-sets.iconify.design/flowbite/sort-solid/",
			"Iconify. (n.d.). Down Icon. Retrieved from https://icon-sets.iconify.design/icon-park/down/",
			"Iconify. (n.d.). Graph Arrow Increase Icon. Retrieved from https://icon-sets.iconify.design/streamline/graph-arrow-increase-solid/",
			"Iconify. (n.d.). Factory Icon. Retrieved from https://icon-sets.iconify.design/material-symbols/factory/",
			"Iconify. (n.d.). Account Icon. Retrieved from https://icon-sets.iconify.design/mdi/account/",
			"Iconify. (n.d.). Menu Icon. Retrieved from https://icon-sets.iconify.design/mingcute/menu-fill/",
			"Iconify. (n.d.). Check Icon. Retrieved from https://icon-sets.iconify.design/mingcute/check-fill/",
		],
	},
];

export default sources;
