const sources = [
    {
        name: "Product Images",
        sources: [
            "https://www.homedepot.com/c/ab/types-of-led-lights/9ba683603be9fa5395fab9011a91d53",
            "https://restechtoday.com/does-an-energy-monitor-really-add-value-to-a-smart-home/",
            "https://www.reviews.org/home-security/best-smart-thermostats/",
            "https://www.treehugger.com/energy-efficient-refrigerators-5193342",
            "https://www.tnmagazine.org/is-a-geothermal-heat-pump-right-for-you/",
            "https://www.micro-hydro-power.com/",
            "https://www.altestore.com/diy-solar-resources/residential-wind-turbines-practical-for-you/",
            "https://www.lowimpact.org/posts/composting-toilets-and-city-flats-do-they-match",
            "https://www.homedepot.com/c/ab/best-high-efficiency-washing-machines-for-your-home/9ba683603be9fa5395fab90c4e9a308",
            "https://vaswcd.org/permeable-pavement-installation/",
            "https://www.zone7water.com/post/rebate-smart-irrigation-controllers",
            "https://www.5280.com/5-xeriscaping-myths-debunked/",
            "https://lawnlove.com/blog/benefits-of-drip-irrigation/",
            "https://www.computerworld.com/article/3069499/sunrun-begins-installing-tesla-home-batteries.html",
            "https://www.watts.com/solutions/systems/hydronic-heating-systems",
            "https://www.verywellfit.com/whats-typical-for-average-daily-steps-3435736",
            "https://www.homedepot.com/p/US-Stove-Wiseway-2-000-sq-ft-40-000-BTU-Non-Electric-Gravity-Fed-Pellet-Stove-GW1949/206691061",
            "https://energysavingtrust.org.uk/advice/solar-water-heating/",
            "https://modernize.com/homeowner-resources/hvac/electric-boiler-when-to-use-one-and-what-it-costs-to-run",
            "https://www.unc.edu/discover/infrastructure-needed-for-e-scooter-safety/",
            "https://cars.usnews.com/cars-trucks/advice/cheapest-hybrid-cars",
            "https://www.ftc.net/business/blog/tools-needed-for-telecommuting/",
            "https://www.maskmatters.org/carpool/",
            "https://www.portseattle.org/sea-tac/ground-transportation/public-transit",
            "https://www.grassracks.com/products/bike-wall-rack",
            "https://www.forbes.com/home-improvement/insulation/cost-to-install-wall-insulation/",
            "https://www.chinadaily.com.cn/business/motoring/2017-06/05/content_29614147.htm",
            "https://www.ebay.com/itm/145547420112",
            "https://www.tank-depot.com/enduraplas-60-inch-wide-870-gallon-plastic-vertical-rainwater-harvesting-tank-in-black-ep-tlv00870bk-rh?cq_src=google_ads&cq_cmp=18259210262&cq_con=&cq_term=&cq_med=pla&cq_plac=&cq_net=x&cq_pos=&cq_plt=gpition}&cq_plt=gp&campaignid=18259210262&adgroupid=&creative=&matchtype=&network=x&device=c&keyword=EP-TLV00870BK-RH&gad_source=1&gclid=CjwKCAiAloavBhBOEiwAbtAJO9yOjDdmqqPKHras1g5GHFi-26tEO6ZJ1XWDpJu7CkiC6EIlt9cnDhoC-R0QAvD_BwE",
            "https://www.builderonline.com/products/green-products/low-flow-fixtures-from-fluid_o",
            "https://completelandscaping.com/xeriscaping-can-help-save-water/",
            "https://www.agrivi.com/blog/drip-irrigation-as-the-most-efficient-irrigation-system-type/",
            "https://www.tavistock-bathrooms.co.uk/quantum-dual-function-shower-system-with-handset-holder-overhead-shower-chrome",
            "https://www.amazon.com/NINILADY-Vertical-Turbine-Generator-Controller/dp/B08MQ8PQ7D",
            "https://www.treehugger.com/energy-efficient-refrigerators-5193342",
            "https://www.techhive.com/article/578519/ring-a19-smart-led-bulb-review.html",
            "https://aspaen.edu.co/?w=google-nest-learning-smart-wifi-thermostat-black-t3018us-best-ee-o27Y4OhZ",
            "https://www.pmcarchitects.com/sustainability-information-blog-content/when-will-a-tesla-home-battery-pay-for-itself",
            "https://en.wikipedia.org/wiki/Carsharing",
            "https://www.cars.com/articles/what-are-hydrogen-cars-442319/",
            "https://www.freepik.com/premium-photo/web-conference-business-online-corporate-telecommuting-man-holding-laptop-with-professional-team-working-project-screen-virtual-office-isolated-black_24955614.htm",
            "https://ny.curbed.com/2018/1/30/16946476/mta-new-york-city-bus-operating-costs-analysis",
            "https://www.caranddriver.com/tesla/model-s-2023",
            "https://www.etsy.com/listing/1048894021/rustic-kentucky-crapper-composting",
            "https://www.lowes.com/pd/Rubbermaid-Commercial-Products-Brute-50-Gallon-Blue-Commercial-Outdoor-Recycling-Bin-with-Lid/50335461",
            "https://www.architectureanddesign.com.au/features/comment/passive-solar-design-vs-passive-house",
            "https://americanthermalwindow.com/benefits-triple-pane-windows/",
            "https://www.acehardware.com/departments/plumbing/winterization/pipe-insulation/4565685?x429=true&gad_source=1&gclid=CjwKCAiAloavBhBOEiwAbtAJO6TB71_FNCmHT9v3fwMZhPzks7am3pOS1vLMBFlMZ9U_KITgnmPpARoCnTMQAvD_BwE&gclsrc=aw.ds",
            "https://airmanagement.com/heat-pumps/",
            "https://www.completeinsulations.ie/earthwool-attic-insulation/",
            "https://www.lg.com/us/washers-dryers/lg-wm3470cm-front-load-washer",
            "https://www.fujibikes.com/products/absolute-21-21",
            "https://www.weil-mclain.com/full-line",
            
        ],
    },
];

export default sources;
